// Slim env type declarations extracted from cloudflare-env.d.ts.
// The full file (generated by `wrangler types`) includes 11K+ lines of Cloudflare
// runtime type definitions that cause a TypeScript stack overflow during control
// flow analysis. This file provides only the ambient env declarations needed by
// the project. Re-run `wrangler types` to update the full file, then copy the
// Env interface here if bindings change.
//
// Types for R2Bucket, D1Database, Hyperdrive, Fetcher, Service come from
// @cloudflare/workers-types (included via tsconfig).

declare namespace Cloudflare {
  interface Env {
    R2: R2Bucket;
    NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
    NEXT_TAG_CACHE_D1: D1Database;
    HYPERDRIVE: Hyperdrive;
    COCKROACH_HYPERDRIVE: Hyperdrive;
    ASSETS: Fetcher;
    PAYLOAD_SECRET: string;
    PREVIEW_SECRET: string;
    DEFAULT_TENANT_SLUG: string;
    DATABASE_URL: string;
    CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: string;
    COCKROACH_DATABASE_URL: string;
    CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_COCKROACH_HYPERDRIVE: string;
    OPENAI_API_KEY: string;
    WORKER_SELF_REFERENCE: Fetcher;
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PAYLOAD_SECRET" | "PREVIEW_SECRET" | "DEFAULT_TENANT_SLUG" | "DATABASE_URL" | "CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE" | "COCKROACH_DATABASE_URL" | "CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_COCKROACH_HYPERDRIVE" | "OPENAI_API_KEY">> {}
}
