/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconField".
 */
export type IconField =
  | (
      | 'award-01'
      | 'bar-chart-01'
      | 'briefcase-01'
      | 'certificate-01'
      | 'check-circle'
      | 'clock'
      | 'file-check-01'
      | 'globe-01'
      | 'heart'
      | 'lightbulb-01'
      | 'lightning-01'
      | 'rocket-01'
      | 'shield-tick'
      | 'star-01'
      | 'target-01'
      | 'thumbs-up'
      | 'trend-up-01'
      | 'trophy-01'
      | 'users-01'
      | 'zap'
    )
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'industry-categories': IndustryCategory;
    industries: Industry;
    'job-titles': JobTitle;
    'resume-content': ResumeContent;
    sources: Source;
    'content-variations': ContentVariation;
    'word-form-sets': WordFormSet;
    'template-overrides': TemplateOverride;
    tenants: Tenant;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'industry-categories': {
      industries: 'industries';
    };
    industries: {
      jobTitles: 'job-titles';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'industry-categories': IndustryCategoriesSelect<false> | IndustryCategoriesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'job-titles': JobTitlesSelect<false> | JobTitlesSelect<true>;
    'resume-content': ResumeContentSelect<false> | ResumeContentSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'content-variations': ContentVariationsSelect<false> | ContentVariationsSelect<true>;
    'word-form-sets': WordFormSetsSelect<false> | WordFormSetsSelect<true>;
    'template-overrides': TemplateOverridesSelect<false> | TemplateOverridesSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'default-templates': DefaultTemplate;
    header: Header;
    'suffix-variations': SuffixVariation;
  };
  globalsSelect: {
    'default-templates': DefaultTemplatesSelect<false> | DefaultTemplatesSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'suffix-variations': SuffixVariationsSelect<false> | SuffixVariationsSelect<true>;
  };
  locale: 'en' | 'es';
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      generateSearchEmbedding: TaskGenerateSearchEmbedding;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: 'super-admin'[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'editor')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-safe identifier for this tenant
   */
  slug: string;
  /**
   * Custom domain for this tenant
   */
  domain?: string | null;
  /**
   * Locales available for this tenant
   */
  supportedLocales?: ('en' | 'es')[] | null;
  /**
   * Controls which industries this tenant generates pages for.
   */
  industryMode?: ('all' | 'include' | 'exclude') | null;
  /**
   * Industries to include or exclude based on mode.
   */
  industries?: (number | Industry)[] | null;
  /**
   * Controls which job titles within the selected industries this tenant serves.
   */
  jobTitleMode?: ('all-in-industries' | 'specific' | 'exclude-specific') | null;
  /**
   * Specific job titles to include.
   */
  jobTitles?: (number | JobTitle)[] | null;
  /**
   * Specific job titles to exclude.
   */
  excludedJobTitles?: (number | JobTitle)[] | null;
  keywordLandings?: {
    enabled?: boolean | null;
    mode?: ('all' | 'include' | 'exclude') | null;
    /**
     * Glob patterns using * as wildcard. E.g., "best-*", "*-resume-*", "free-*-templates"
     */
    patterns?:
      | {
          pattern: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  category?: (number | null) | IndustryCategory;
  description?: string | null;
  jobTitles?: {
    docs?: (number | JobTitle)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Where this data originated
   */
  origin?: {
    source?: (number | null) | Source;
    importedAt?: string | null;
    /**
     * Optional: batch ID, file name, external ID, etc.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-categories".
 */
export interface IndustryCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  industries?: {
    docs?: (number | Industry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles".
 */
export interface JobTitle {
  id: number;
  name: string;
  industries?: (number | Industry)[] | null;
  suggestedContent?:
    | {
        content: number | ResumeContent;
        /**
         * Supply-side: do professionals in this role report this? (0-1)
         */
        experienceScore?: number | null;
        /**
         * Demand-side: do job seekers for this role search for this? (0-1)
         */
        interestScore?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Override the default canonical suffix for this job title. When unchecked, the global canonical suffix from Suffix Variations is used.
   */
  overrideSuffix?: boolean | null;
  /**
   * Adjective word for canonical suffix (e.g., "best")
   */
  suffixAdjective?: (number | null) | WordFormSet;
  /**
   * Builder word for canonical suffix (e.g., "creator")
   */
  suffixBuilder?: (number | null) | WordFormSet;
  /**
   * Content word for canonical suffix (e.g., "content")
   */
  suffixContentWord?: (number | null) | WordFormSet;
  /**
   * Override the global canonical strategy for this job title.
   */
  suffixStrategy?: ('redirect-301' | 'redirect-302' | 'rel-canonical') | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Confidence this is a real job title (1.0 = SOC/O*NET verified)
   */
  probability?: number | null;
  /**
   * Where this data originated
   */
  origin?: {
    source?: (number | null) | Source;
    importedAt?: string | null;
    /**
     * Optional: batch ID, file name, external ID, etc.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-content".
 */
export interface ResumeContent {
  id: number;
  type: 'skill' | 'experience' | 'summary' | 'accomplishment' | 'affiliation' | 'certification';
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * The content text (experience bullet, summary paragraph, skill phrase, etc.)
   */
  description?: string | null;
  /**
   * Where this data originated
   */
  origin?: {
    source?: (number | null) | Source;
    importedAt?: string | null;
    /**
     * Optional: batch ID, file name, external ID, etc.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Optional context about this data source.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "word-form-sets".
 */
export interface WordFormSet {
  id: number;
  name: string;
  /**
   * Which category of word forms this entry defines
   */
  type: 'resumeWord' | 'verb' | 'adjective' | 'contentWord';
  /**
   * Leave empty for a global default. Set to override for a specific tenant.
   */
  tenant?: (number | null) | Tenant;
  /**
   * e.g., "resume", "CV", "curriculum vitae"
   */
  rw_singular?: string | null;
  /**
   * e.g., "resumes", "CVs", "curricula vitae"
   */
  rw_plural?: string | null;
  /**
   * e.g., "Resume", "CV", "Curriculum Vitae"
   */
  rw_capitalized?: string | null;
  /**
   * e.g., "resume", "CV"
   */
  rw_abbreviated?: string | null;
  /**
   * e.g., "Resume", "CV"
   */
  rw_abbreviatedCapitalized?: string | null;
  /**
   * e.g., "Resumes", "CVs"
   */
  rw_pluralCapitalized?: string | null;
  /**
   * e.g., "resumes", "CVs"
   */
  rw_pluralAbbreviated?: string | null;
  /**
   * e.g., "Resumes", "CVs"
   */
  rw_pluralAbbreviatedCapitalized?: string | null;
  /**
   * The URL suffix word, e.g., "creator", "builder", "maker"
   */
  v_worder?: string | null;
  /**
   * e.g., "create", "build", "make"
   */
  v_singular?: string | null;
  /**
   * e.g., "Create", "Build"
   */
  v_capitalized?: string | null;
  /**
   * e.g., "Creator", "Builder"
   */
  v_worderCapitalized?: string | null;
  /**
   * e.g., "creating", "building"
   */
  v_wording?: string | null;
  /**
   * e.g., "Creating", "Building"
   */
  v_wordingCapitalized?: string | null;
  /**
   * e.g., "created", "built", "wrote"
   */
  v_past?: string | null;
  /**
   * e.g., "Created", "Built"
   */
  v_pastCapitalized?: string | null;
  /**
   * e.g., "best", "professional", "simple"
   */
  adj_singular?: string | null;
  /**
   * e.g., "Best", "Professional"
   */
  adj_capitalized?: string | null;
  /**
   * e.g., "better", "professionally", "easier"
   */
  adj_adverb?: string | null;
  /**
   * e.g., "Better", "Professionally"
   */
  adj_adverbCapitalized?: string | null;
  /**
   * e.g., "template", "example", "content"
   */
  cw_singular?: string | null;
  /**
   * e.g., "templates", "examples", "content" (same for uncountable)
   */
  cw_plural?: string | null;
  /**
   * e.g., "Template", "Content"
   */
  cw_capitalized?: string | null;
  /**
   * e.g., "Templates", "Content"
   */
  cw_pluralCapitalized?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  hero?: HeroSplitBlock[] | null;
  layout?: (BlogBlock | TestimonialsBlock | MetricsBlock | CTABlock)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  author?: (number | null) | User;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock".
 */
export interface HeroSplitBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  image?: (number | null) | Media;
  form?: {
    placeholder?: string | null;
    buttonLabel?: string | null;
    helperText?: string | null;
  };
  review?: {
    text?: string | null;
    rating?: string | null;
    avatars?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variations".
 */
export interface ContentVariation {
  id: number;
  name: string;
  /**
   * Auto-generated dot-notation key from name (e.g. hero.title). Uses a beforeValidate hook or slugField-like approach to derive from the name field.
   */
  assignmentKey?: string | null;
  parent?: (number | null) | ContentVariation;
  options?:
    | {
        text?: string | null;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock".
 */
export interface BlogBlock {
  label?: string | null;
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  formPlaceholder?: string | null;
  formButtonLabel?: string | null;
  articles?:
    | {
        title?: string | null;
        summary?: string | null;
        href?: string | null;
        categoryName?: string | null;
        thumbnail?: (number | null) | Media;
        publishedAt?: string | null;
        readingTime?: string | null;
        authorName?: string | null;
        authorImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  reviews?:
    | {
        quote?: string | null;
        authorName?: string | null;
        authorTitle?: string | null;
        authorImage?: (number | null) | Media;
        companyName?: string | null;
        /**
         * Light mode logo
         */
        companyLogo?: (number | null) | Media;
        /**
         * Dark mode logo
         */
        companyLogoDark?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  metrics?:
    | {
        icon?: IconField;
        label?: string | null;
        description?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  /**
   * CTA buttons displayed below the description
   */
  links?:
    | {
        link?: LinkField;
        variant?: ('primary' | 'secondary' | 'tertiary' | 'link-gray' | 'link-color') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkField".
 */
export interface LinkField {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  reference?: {
    relationTo: 'pages';
    value: number | Page;
  } | null;
  url?: string | null;
  label?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-overrides".
 */
export interface TemplateOverride {
  id: number;
  /**
   * Human-readable label for this override
   */
  name: string;
  /**
   * Leave empty for a global override
   */
  tenant?: (number | null) | Tenant;
  targetType?: ('industry-category' | 'industry' | 'job-title' | 'keyword-landing') | null;
  targetEntity?:
    | ({
        relationTo: 'industry-categories';
        value: number | IndustryCategory;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'job-titles';
        value: number | JobTitle;
      } | null);
  /**
   * Glob pattern for keyword landing slugs. Use * as wildcard. Examples: *, free-resume-*, *-resume-builder
   */
  targetPattern?: string | null;
  sectionOverrides?:
    | {
        /**
         * Which block type this override applies to
         */
        sectionBlockType?: ('heroSplit' | 'blog' | 'testimonials' | 'metrics' | 'cta') | null;
        action?: ('hide' | 'override-props') | null;
        /**
         * When locked, tenant overrides cannot modify this section.
         */
        locked?: boolean | null;
        /**
         * Override the section ordering group
         */
        sectionGroup?: ('before' | 'test' | 'after') | null;
        ovrds_heroSplit?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_blog?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_testimonials?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_metrics?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_cta?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        /**
         * JSON escape hatch for overrides not covered by the UI fields. Top-level keys must match block field names.
         */
        advancedOverrides?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  contentVariations?: {
    /**
     * Allow clients to find content-variations.
     */
    find?: boolean | null;
    /**
     * Allow clients to create content-variations.
     */
    create?: boolean | null;
    /**
     * Allow clients to update content-variations.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete content-variations.
     */
    delete?: boolean | null;
  };
  templateOverrides?: {
    /**
     * Allow clients to find template-overrides.
     */
    find?: boolean | null;
    /**
     * Allow clients to create template-overrides.
     */
    create?: boolean | null;
    /**
     * Allow clients to update template-overrides.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete template-overrides.
     */
    delete?: boolean | null;
  };
  resumeContent?: {
    /**
     * Allow clients to find resume-content.
     */
    find?: boolean | null;
    /**
     * Allow clients to create resume-content.
     */
    create?: boolean | null;
    /**
     * Allow clients to update resume-content.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete resume-content.
     */
    delete?: boolean | null;
  };
  wordFormSets?: {
    /**
     * Allow clients to find word-form-sets.
     */
    find?: boolean | null;
    /**
     * Allow clients to create word-form-sets.
     */
    create?: boolean | null;
    /**
     * Allow clients to update word-form-sets.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete word-form-sets.
     */
    delete?: boolean | null;
  };
  industries?: {
    /**
     * Allow clients to find industries.
     */
    find?: boolean | null;
    /**
     * Allow clients to create industries.
     */
    create?: boolean | null;
    /**
     * Allow clients to update industries.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete industries.
     */
    delete?: boolean | null;
  };
  industryCategories?: {
    /**
     * Allow clients to find industry-categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create industry-categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update industry-categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete industry-categories.
     */
    delete?: boolean | null;
  };
  jobTitles?: {
    /**
     * Allow clients to find job-titles.
     */
    find?: boolean | null;
    /**
     * Allow clients to create job-titles.
     */
    create?: boolean | null;
    /**
     * Allow clients to update job-titles.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete job-titles.
     */
    delete?: boolean | null;
  };
  sources?: {
    /**
     * Allow clients to find sources.
     */
    find?: boolean | null;
    /**
     * Allow clients to create sources.
     */
    create?: boolean | null;
    /**
     * Allow clients to update sources.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete sources.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  tenants?: {
    /**
     * Allow clients to find tenants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tenants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tenants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tenants.
     */
    delete?: boolean | null;
  };
  defaultTemplates?: {
    /**
     * Allow clients to find default-templates global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update default-templates global.
     */
    update?: boolean | null;
  };
  suffixVariations?: {
    /**
     * Allow clients to find suffix-variations global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update suffix-variations global.
     */
    update?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update header global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'job-titles';
        value: number | JobTitle;
      }
    | {
        relationTo: 'resume-content';
        value: number | ResumeContent;
      };
  fullText?: string | null;
  sourceSlug?: string | null;
  industrySlug?: string | null;
  suffixAdjective?: string | null;
  suffixResumeWord?: string | null;
  suffixBuilder?: string | null;
  suffixContentWord?: string | null;
  contentType?: string | null;
  hasEmbedding?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateSearchEmbedding' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'generateSearchEmbedding' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'industry-categories';
        value: number | IndustryCategory;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'job-titles';
        value: number | JobTitle;
      } | null)
    | ({
        relationTo: 'resume-content';
        value: number | ResumeContent;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'content-variations';
        value: number | ContentVariation;
      } | null)
    | ({
        relationTo: 'word-form-sets';
        value: number | WordFormSet;
      } | null)
    | ({
        relationTo: 'template-overrides';
        value: number | TemplateOverride;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  hero?:
    | T
    | {
        heroSplit?: T | HeroSplitBlockSelect<T>;
      };
  layout?:
    | T
    | {
        blog?: T | BlogBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  author?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock_select".
 */
export interface HeroSplitBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  image?: T;
  form?:
    | T
    | {
        placeholder?: T;
        buttonLabel?: T;
        helperText?: T;
      };
  review?:
    | T
    | {
        text?: T;
        rating?: T;
        avatars?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock_select".
 */
export interface BlogBlockSelect<T extends boolean = true> {
  label?: T;
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  formPlaceholder?: T;
  formButtonLabel?: T;
  articles?:
    | T
    | {
        title?: T;
        summary?: T;
        href?: T;
        categoryName?: T;
        thumbnail?: T;
        publishedAt?: T;
        readingTime?: T;
        authorName?: T;
        authorImage?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  reviews?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorTitle?: T;
        authorImage?: T;
        companyName?: T;
        companyLogo?: T;
        companyLogoDark?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock_select".
 */
export interface MetricsBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  metrics?:
    | T
    | {
        icon?: T;
        label?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  links?:
    | T
    | {
        link?: T | LinkFieldSelect<T>;
        variant?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkField_select".
 */
export interface LinkFieldSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  reference?: T;
  url?: T;
  label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-categories_select".
 */
export interface IndustryCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  industries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  jobTitles?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  generateSlug?: T;
  slug?: T;
  origin?:
    | T
    | {
        source?: T;
        importedAt?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles_select".
 */
export interface JobTitlesSelect<T extends boolean = true> {
  name?: T;
  industries?: T;
  suggestedContent?:
    | T
    | {
        content?: T;
        experienceScore?: T;
        interestScore?: T;
        id?: T;
      };
  overrideSuffix?: T;
  suffixAdjective?: T;
  suffixBuilder?: T;
  suffixContentWord?: T;
  suffixStrategy?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  generateSlug?: T;
  slug?: T;
  probability?: T;
  origin?:
    | T
    | {
        source?: T;
        importedAt?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-content_select".
 */
export interface ResumeContentSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  origin?:
    | T
    | {
        source?: T;
        importedAt?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variations_select".
 */
export interface ContentVariationsSelect<T extends boolean = true> {
  name?: T;
  assignmentKey?: T;
  parent?: T;
  options?:
    | T
    | {
        text?: T;
        weight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "word-form-sets_select".
 */
export interface WordFormSetsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  tenant?: T;
  rw_singular?: T;
  rw_plural?: T;
  rw_capitalized?: T;
  rw_abbreviated?: T;
  rw_abbreviatedCapitalized?: T;
  rw_pluralCapitalized?: T;
  rw_pluralAbbreviated?: T;
  rw_pluralAbbreviatedCapitalized?: T;
  v_worder?: T;
  v_singular?: T;
  v_capitalized?: T;
  v_worderCapitalized?: T;
  v_wording?: T;
  v_wordingCapitalized?: T;
  v_past?: T;
  v_pastCapitalized?: T;
  adj_singular?: T;
  adj_capitalized?: T;
  adj_adverb?: T;
  adj_adverbCapitalized?: T;
  cw_singular?: T;
  cw_plural?: T;
  cw_capitalized?: T;
  cw_pluralCapitalized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-overrides_select".
 */
export interface TemplateOverridesSelect<T extends boolean = true> {
  name?: T;
  tenant?: T;
  targetType?: T;
  targetEntity?: T;
  targetPattern?: T;
  sectionOverrides?:
    | T
    | {
        sectionBlockType?: T;
        action?: T;
        locked?: T;
        sectionGroup?: T;
        ovrds_heroSplit?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_blog?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_testimonials?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_metrics?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_cta?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        advancedOverrides?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  supportedLocales?: T;
  industryMode?: T;
  industries?: T;
  jobTitleMode?: T;
  jobTitles?: T;
  excludedJobTitles?: T;
  keywordLandings?:
    | T
    | {
        enabled?: T;
        mode?: T;
        patterns?:
          | T
          | {
              pattern?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  contentVariations?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  templateOverrides?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  resumeContent?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  wordFormSets?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  industries?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  industryCategories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  jobTitles?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  sources?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  tenants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  defaultTemplates?:
    | T
    | {
        find?: T;
        update?: T;
      };
  suffixVariations?:
    | T
    | {
        find?: T;
        update?: T;
      };
  header?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  fullText?: T;
  sourceSlug?: T;
  industrySlug?: T;
  suffixAdjective?: T;
  suffixResumeWord?: T;
  suffixBuilder?: T;
  suffixContentWord?: T;
  contentType?: T;
  hasEmbedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-templates".
 */
export interface DefaultTemplate {
  id: number;
  jobTitle?: {
    hero?: HeroSplitBlock[] | null;
    sections?: (BlogBlock | TestimonialsBlock | MetricsBlock | CTABlock)[] | null;
  };
  industry?: {
    hero?: HeroSplitBlock[] | null;
    sections?: (BlogBlock | TestimonialsBlock | MetricsBlock | CTABlock)[] | null;
  };
  keyword?: {
    /**
     * Define URL patterns for keyword landing pages. Each pattern generates pages from word pool combinations. Defaults: $(resume)-$(verber), $(resume)-$(contentWord), $(adjective)-$(resume)-$(verber), $(adjective)-$(resume)-$(contentWord), $(adjective)-$(resume)-$(verber)-$(contentWord)
     */
    patterns?:
      | {
          /**
           * URL template. Variables: $(resume), $(verb), $(verber), $(adjective), $(contentWord). Literals like "how-to-" are kept as-is.
           */
          pattern: string;
          id?: string | null;
        }[]
      | null;
    hero?: HeroSplitBlock[] | null;
    sections?: (BlogBlock | TestimonialsBlock | MetricsBlock | CTABlock)[] | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        type?: ('link' | 'dropdown') | null;
        link?: LinkField;
        label?: string | null;
        dropdownItems?:
          | {
              link?: LinkField;
              subtitle?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suffix-variations".
 */
export interface SuffixVariation {
  id: number;
  /**
   * Resume words used in suffix and keyword generation. E.g., resume, cv, curriculum-vitae.
   */
  resumeWords?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        /**
         * Use this word in the canonical suffix URL
         */
        isCanonical?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Adjective words used in suffix generation. Pattern: {adjective}-resume-{builder}-{content}
   */
  adjectives?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        /**
         * Use this word in the canonical suffix URL
         */
        isCanonical?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Builder words used in suffix generation.
   */
  builders?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        /**
         * Use this word in the canonical suffix URL
         */
        isCanonical?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Content words used in suffix generation.
   */
  contentWords?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        /**
         * Use this word in the canonical suffix URL
         */
        isCanonical?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default number of suffix URLs to generate per page.
   */
  defaultSuffixCount?: number | null;
  /**
   * How to handle non-canonical suffix URLs. Redirect sends users to the canonical URL. rel="canonical" renders the page but tells search engines which URL is preferred.
   */
  canonicalStrategy?: ('redirect-301' | 'redirect-302' | 'rel-canonical') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-templates_select".
 */
export interface DefaultTemplatesSelect<T extends boolean = true> {
  jobTitle?:
    | T
    | {
        hero?:
          | T
          | {
              heroSplit?: T | HeroSplitBlockSelect<T>;
            };
        sections?:
          | T
          | {
              blog?: T | BlogBlockSelect<T>;
              testimonials?: T | TestimonialsBlockSelect<T>;
              metrics?: T | MetricsBlockSelect<T>;
              cta?: T | CTABlockSelect<T>;
            };
      };
  industry?:
    | T
    | {
        hero?:
          | T
          | {
              heroSplit?: T | HeroSplitBlockSelect<T>;
            };
        sections?:
          | T
          | {
              blog?: T | BlogBlockSelect<T>;
              testimonials?: T | TestimonialsBlockSelect<T>;
              metrics?: T | MetricsBlockSelect<T>;
              cta?: T | CTABlockSelect<T>;
            };
      };
  keyword?:
    | T
    | {
        patterns?:
          | T
          | {
              pattern?: T;
              id?: T;
            };
        hero?:
          | T
          | {
              heroSplit?: T | HeroSplitBlockSelect<T>;
            };
        sections?:
          | T
          | {
              blog?: T | BlogBlockSelect<T>;
              testimonials?: T | TestimonialsBlockSelect<T>;
              metrics?: T | MetricsBlockSelect<T>;
              cta?: T | CTABlockSelect<T>;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        type?: T;
        link?: T | LinkFieldSelect<T>;
        label?: T;
        dropdownItems?:
          | T
          | {
              link?: T | LinkFieldSelect<T>;
              subtitle?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suffix-variations_select".
 */
export interface SuffixVariationsSelect<T extends boolean = true> {
  resumeWords?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        isCanonical?: T;
        id?: T;
      };
  adjectives?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        isCanonical?: T;
        id?: T;
      };
  builders?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        isCanonical?: T;
        id?: T;
      };
  contentWords?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        isCanonical?: T;
        id?: T;
      };
  defaultSuffixCount?: T;
  canonicalStrategy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateSearchEmbedding".
 */
export interface TaskGenerateSearchEmbedding {
  input: {
    docId: number;
    collection: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}