/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    pages: Page;
    'industry-categories': IndustryCategory;
    industries: Industry;
    'job-titles': JobTitle;
    skills: Skill;
    'content-variations': ContentVariation;
    'word-form-sets': WordFormSet;
    'template-overrides': TemplateOverride;
    'tenant-page-configs': TenantPageConfig;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'industry-categories': {
      industries: 'industries';
    };
    industries: {
      jobTitles: 'job-titles';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'industry-categories': IndustryCategoriesSelect<false> | IndustryCategoriesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'job-titles': JobTitlesSelect<false> | JobTitlesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'content-variations': ContentVariationsSelect<false> | ContentVariationsSelect<true>;
    'word-form-sets': WordFormSetsSelect<false> | WordFormSetsSelect<true>;
    'template-overrides': TemplateOverridesSelect<false> | TemplateOverridesSelect<true>;
    'tenant-page-configs': TenantPageConfigsSelect<false> | TenantPageConfigsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'default-industry-template': DefaultIndustryTemplate;
    'default-job-title-template': DefaultJobTitleTemplate;
    'suffix-variations': SuffixVariation;
  };
  globalsSelect: {
    'default-industry-template': DefaultIndustryTemplateSelect<false> | DefaultIndustryTemplateSelect<true>;
    'default-job-title-template': DefaultJobTitleTemplateSelect<false> | DefaultJobTitleTemplateSelect<true>;
    'suffix-variations': SuffixVariationsSelect<false> | SuffixVariationsSelect<true>;
  };
  locale: 'en' | 'es';
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: 'super-admin'[] | null;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'editor')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-safe identifier for this tenant
   */
  slug: string;
  /**
   * Custom domain for this tenant
   */
  domain?: string | null;
  /**
   * Locales available for this tenant
   */
  supportedLocales?: ('en' | 'es')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  hero?: HeroSplitBlock[] | null;
  layout?: (BlogBlock | TestimonialsBlock | MetricsBlock)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  author?: (number | null) | User;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock".
 */
export interface HeroSplitBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  image?: (number | null) | Media;
  form?: {
    placeholder?: string | null;
    buttonLabel?: string | null;
    helperText?: string | null;
  };
  review?: {
    text?: string | null;
    rating?: string | null;
    avatars?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variations".
 */
export interface ContentVariation {
  id: number;
  name: string;
  /**
   * Auto-generated dot-notation key from name (e.g. hero.title). Uses a beforeValidate hook or slugField-like approach to derive from the name field.
   */
  assignmentKey?: string | null;
  parent?: (number | null) | ContentVariation;
  options?:
    | {
        text?: string | null;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock".
 */
export interface BlogBlock {
  label?: string | null;
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  formPlaceholder?: string | null;
  formButtonLabel?: string | null;
  articles?:
    | {
        title?: string | null;
        summary?: string | null;
        href?: string | null;
        categoryName?: string | null;
        thumbnail?: (number | null) | Media;
        publishedAt?: string | null;
        readingTime?: string | null;
        authorName?: string | null;
        authorImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  reviews?:
    | {
        quote?: string | null;
        authorName?: string | null;
        authorTitle?: string | null;
        authorImage?: (number | null) | Media;
        companyName?: string | null;
        /**
         * Light mode logo
         */
        companyLogo?: (number | null) | Media;
        /**
         * Dark mode logo
         */
        companyLogoDark?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  heading?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  description?: {
    mode?: ('fixed' | 'variation') | null;
    fixedText?: string | null;
    variationSet?: (number | null) | ContentVariation;
  };
  metrics?:
    | {
        value?: string | null;
        label?: string | null;
        description?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated identifier for this section. Used as merge key for template overrides.
   */
  sectionId?: string | null;
  /**
   * Controls section ordering group. "Test" sections are shuffled for A/B testing.
   */
  sectionGroup?: ('before' | 'test' | 'after') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-categories".
 */
export interface IndustryCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  industries?: {
    docs?: (number | Industry)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category?: (number | null) | IndustryCategory;
  description?: string | null;
  jobTitles?: {
    docs?: (number | JobTitle)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles".
 */
export interface JobTitle {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  industries?: (number | Industry)[] | null;
  suggestedSkills?: (number | Skill)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * Allow search engines to index this page
     */
    robots?: ('index' | 'noindex') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category?: ('technical' | 'soft' | 'certification') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "word-form-sets".
 */
export interface WordFormSet {
  id: number;
  name: string;
  /**
   * Which category of word forms this entry defines
   */
  type: 'resumeWord' | 'verb' | 'adjective' | 'contentWord';
  /**
   * Leave empty for a global default. Set to override for a specific tenant.
   */
  tenant?: (number | null) | Tenant;
  /**
   * e.g., "resume", "CV", "curriculum vitae"
   */
  rw_singular?: string | null;
  /**
   * e.g., "resumes", "CVs", "curricula vitae"
   */
  rw_plural?: string | null;
  /**
   * e.g., "Resume", "CV", "Curriculum Vitae"
   */
  rw_capitalized?: string | null;
  /**
   * e.g., "resume", "CV"
   */
  rw_abbreviated?: string | null;
  /**
   * e.g., "Resume", "CV"
   */
  rw_abbreviatedCapitalized?: string | null;
  /**
   * e.g., "Resumes", "CVs"
   */
  rw_pluralCapitalized?: string | null;
  /**
   * e.g., "resumes", "CVs"
   */
  rw_pluralAbbreviated?: string | null;
  /**
   * e.g., "Resumes", "CVs"
   */
  rw_pluralAbbreviatedCapitalized?: string | null;
  /**
   * The URL suffix word, e.g., "creator", "builder", "maker"
   */
  v_worder?: string | null;
  /**
   * e.g., "create", "build", "make"
   */
  v_singular?: string | null;
  /**
   * e.g., "Create", "Build"
   */
  v_capitalized?: string | null;
  /**
   * e.g., "Creator", "Builder"
   */
  v_worderCapitalized?: string | null;
  /**
   * e.g., "creating", "building"
   */
  v_wording?: string | null;
  /**
   * e.g., "Creating", "Building"
   */
  v_wordingCapitalized?: string | null;
  /**
   * e.g., "created", "built", "wrote"
   */
  v_past?: string | null;
  /**
   * e.g., "Created", "Built"
   */
  v_pastCapitalized?: string | null;
  /**
   * e.g., "best", "professional", "simple"
   */
  adj_singular?: string | null;
  /**
   * e.g., "Best", "Professional"
   */
  adj_capitalized?: string | null;
  /**
   * e.g., "better", "professionally", "easier"
   */
  adj_adverb?: string | null;
  /**
   * e.g., "Better", "Professionally"
   */
  adj_adverbCapitalized?: string | null;
  /**
   * e.g., "template", "example", "content"
   */
  cw_singular?: string | null;
  /**
   * e.g., "templates", "examples", "content" (same for uncountable)
   */
  cw_plural?: string | null;
  /**
   * e.g., "Template", "Content"
   */
  cw_capitalized?: string | null;
  /**
   * e.g., "Templates", "Content"
   */
  cw_pluralCapitalized?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-overrides".
 */
export interface TemplateOverride {
  id: number;
  /**
   * Human-readable label for this override
   */
  name: string;
  /**
   * Leave empty for a global override
   */
  tenant?: (number | null) | Tenant;
  targetType?: ('industry-category' | 'industry' | 'job-title') | null;
  targetEntity?:
    | ({
        relationTo: 'industry-categories';
        value: number | IndustryCategory;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'job-titles';
        value: number | JobTitle;
      } | null);
  sectionOverrides?:
    | {
        /**
         * Which block type this override applies to
         */
        sectionBlockType?: ('heroSplit' | 'blog' | 'testimonials' | 'metrics') | null;
        action?: ('hide' | 'override-props') | null;
        /**
         * When locked, tenant overrides cannot modify this section.
         */
        locked?: boolean | null;
        /**
         * Override the section ordering group
         */
        sectionGroup?: ('before' | 'test' | 'after') | null;
        ovrds_heroSplit?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_blog?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_testimonials?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        ovrds_metrics?: {
          /**
           * Select which fields to override. Only selected fields will be applied during merge.
           */
          fieldsToOverride?: ('heading' | 'description')[] | null;
          heading?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
          description?: {
            mode?: ('fixed' | 'variation') | null;
            fixedText?: string | null;
            variationSet?: (number | null) | ContentVariation;
          };
        };
        /**
         * JSON escape hatch for overrides not covered by the UI fields. Top-level keys must match block field names.
         */
        advancedOverrides?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-page-configs".
 */
export interface TenantPageConfig {
  id: number;
  /**
   * Each tenant can have exactly one page config.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Controls which industries this tenant generates pages for.
   */
  mode?: ('all' | 'include' | 'exclude') | null;
  /**
   * Industries to include or exclude based on mode.
   */
  industries?: (number | Industry)[] | null;
  /**
   * Controls which job titles within the selected industries this tenant serves.
   */
  jobTitleMode?: ('all-in-industries' | 'specific' | 'exclude-specific') | null;
  /**
   * Specific job titles to include.
   */
  jobTitles?: (number | JobTitle)[] | null;
  /**
   * Specific job titles to exclude.
   */
  excludedJobTitles?: (number | JobTitle)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'industry-categories';
        value: number | IndustryCategory;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'job-titles';
        value: number | JobTitle;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'content-variations';
        value: number | ContentVariation;
      } | null)
    | ({
        relationTo: 'word-form-sets';
        value: number | WordFormSet;
      } | null)
    | ({
        relationTo: 'template-overrides';
        value: number | TemplateOverride;
      } | null)
    | ({
        relationTo: 'tenant-page-configs';
        value: number | TenantPageConfig;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  supportedLocales?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  hero?:
    | T
    | {
        heroSplit?: T | HeroSplitBlockSelect<T>;
      };
  layout?:
    | T
    | {
        blog?: T | BlogBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  author?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock_select".
 */
export interface HeroSplitBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  image?: T;
  form?:
    | T
    | {
        placeholder?: T;
        buttonLabel?: T;
        helperText?: T;
      };
  review?:
    | T
    | {
        text?: T;
        rating?: T;
        avatars?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogBlock_select".
 */
export interface BlogBlockSelect<T extends boolean = true> {
  label?: T;
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  formPlaceholder?: T;
  formButtonLabel?: T;
  articles?:
    | T
    | {
        title?: T;
        summary?: T;
        href?: T;
        categoryName?: T;
        thumbnail?: T;
        publishedAt?: T;
        readingTime?: T;
        authorName?: T;
        authorImage?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  reviews?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorTitle?: T;
        authorImage?: T;
        companyName?: T;
        companyLogo?: T;
        companyLogoDark?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock_select".
 */
export interface MetricsBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  description?:
    | T
    | {
        mode?: T;
        fixedText?: T;
        variationSet?: T;
      };
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        id?: T;
      };
  sectionId?: T;
  sectionGroup?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-categories_select".
 */
export interface IndustryCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  industries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  description?: T;
  jobTitles?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles_select".
 */
export interface JobTitlesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  industries?: T;
  suggestedSkills?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variations_select".
 */
export interface ContentVariationsSelect<T extends boolean = true> {
  name?: T;
  assignmentKey?: T;
  parent?: T;
  options?:
    | T
    | {
        text?: T;
        weight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "word-form-sets_select".
 */
export interface WordFormSetsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  tenant?: T;
  rw_singular?: T;
  rw_plural?: T;
  rw_capitalized?: T;
  rw_abbreviated?: T;
  rw_abbreviatedCapitalized?: T;
  rw_pluralCapitalized?: T;
  rw_pluralAbbreviated?: T;
  rw_pluralAbbreviatedCapitalized?: T;
  v_worder?: T;
  v_singular?: T;
  v_capitalized?: T;
  v_worderCapitalized?: T;
  v_wording?: T;
  v_wordingCapitalized?: T;
  v_past?: T;
  v_pastCapitalized?: T;
  adj_singular?: T;
  adj_capitalized?: T;
  adj_adverb?: T;
  adj_adverbCapitalized?: T;
  cw_singular?: T;
  cw_plural?: T;
  cw_capitalized?: T;
  cw_pluralCapitalized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-overrides_select".
 */
export interface TemplateOverridesSelect<T extends boolean = true> {
  name?: T;
  tenant?: T;
  targetType?: T;
  targetEntity?: T;
  sectionOverrides?:
    | T
    | {
        sectionBlockType?: T;
        action?: T;
        locked?: T;
        sectionGroup?: T;
        ovrds_heroSplit?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_blog?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_testimonials?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        ovrds_metrics?:
          | T
          | {
              fieldsToOverride?: T;
              heading?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
              description?:
                | T
                | {
                    mode?: T;
                    fixedText?: T;
                    variationSet?: T;
                  };
            };
        advancedOverrides?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-page-configs_select".
 */
export interface TenantPageConfigsSelect<T extends boolean = true> {
  tenant?: T;
  mode?: T;
  industries?: T;
  jobTitleMode?: T;
  jobTitles?: T;
  excludedJobTitles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-industry-template".
 */
export interface DefaultIndustryTemplate {
  id: number;
  hero?: HeroSplitBlock[] | null;
  sections?: (BlogBlock | TestimonialsBlock | MetricsBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-job-title-template".
 */
export interface DefaultJobTitleTemplate {
  id: number;
  hero?: HeroSplitBlock[] | null;
  sections?: (BlogBlock | TestimonialsBlock | MetricsBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suffix-variations".
 */
export interface SuffixVariation {
  id: number;
  /**
   * Adjective words used in suffix generation. Pattern: {adjective}-resume-{builder}-{content}
   */
  adjectives?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Builder words used in suffix generation.
   */
  builders?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Content words used in suffix generation.
   */
  contentWords?:
    | {
        wordFormSet: number | WordFormSet;
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default number of suffix URLs to generate per page.
   */
  defaultSuffixCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-industry-template_select".
 */
export interface DefaultIndustryTemplateSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroSplit?: T | HeroSplitBlockSelect<T>;
      };
  sections?:
    | T
    | {
        blog?: T | BlogBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default-job-title-template_select".
 */
export interface DefaultJobTitleTemplateSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroSplit?: T | HeroSplitBlockSelect<T>;
      };
  sections?:
    | T
    | {
        blog?: T | BlogBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suffix-variations_select".
 */
export interface SuffixVariationsSelect<T extends boolean = true> {
  adjectives?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        id?: T;
      };
  builders?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        id?: T;
      };
  contentWords?:
    | T
    | {
        wordFormSet?: T;
        weight?: T;
        id?: T;
      };
  defaultSuffixCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}